# Generated by Django 2.2.5 on 2021-09-30 12:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('alpha', models.FloatField(validators=[django.core.validators.MinValueValidator(0.08), django.core.validators.MaxValueValidator(0.12)])),
                ('beta', models.FloatField(validators=[django.core.validators.MinValueValidator(0.4), django.core.validators.MaxValueValidator(0.6)])),
                ('gamma', models.FloatField(validators=[django.core.validators.MinValueValidator(0.04), django.core.validators.MaxValueValidator(0.06)])),
                ('delta', models.FloatField(validators=[django.core.validators.MinValueValidator(0.008), django.core.validators.MaxValueValidator(0.012)])),
                ('epsilon', models.FloatField(validators=[django.core.validators.MinValueValidator(0.08), django.core.validators.MaxValueValidator(0.12)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
